version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - backend
      - mongo

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports: 
      - 4000:4000
    volumes:
      - ../backend/src:/usr/src/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none